### i. Reproducir la matriz B:
### [[0.4 0.41 0.42 0.43 0.44]
### [0.45 0.46 0.47 0.48 0.49]
### [0.5 0.51 0.52 0.53 0.54]
### [0.55 0.56 0.57 0.58 0.59]
### [0.6 0.61 0.62 0.63 0.64]
### [0.65 0.66 0.67 0.68 0.69]
### [0.7 0.71 0.72 0.73 0.74]
### [0.75 0.76 0.77 0.78 0.79]]

In [103]:
import numpy as np

B = np.arange(0.4,0.8,0.01).reshape(8,5)
B

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

### ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una  matriz de 8 lineas y 13 columnas.


In [104]:
A = np.arange(1,65,1).reshape(8,8)
A = A.T
#Mi compañera de clase me ayudó en esta parte
#Cambiando los valores que tengan 3 por un -99
for indrow, row in enumerate (A): #se corre por fila y se obtiene los indices
    for indcol, element in enumerate (row): #se corre por columnas y se obtiene los indices
        x = str(element) #convertimos a string el indice
        temp = x.find('3') #se encuentra los elementos con el elemento '3'
        if (temp != -1): #se busca los elementos con el -1
            #print(element, indcol, indrow)
            A[indrow, indcol] = -99 #pasamos los indices para cambiar el valor a -99

matriz = np.concatenate((A,B),axis=1)
matriz

array([[  1.  ,   9.  ,  17.  ,  25.  , -99.  ,  41.  ,  49.  ,  57.  ,
          0.4 ,   0.41,   0.42,   0.43,   0.44],
       [  2.  ,  10.  ,  18.  ,  26.  , -99.  ,  42.  ,  50.  ,  58.  ,
          0.45,   0.46,   0.47,   0.48,   0.49],
       [-99.  ,  11.  ,  19.  ,  27.  , -99.  , -99.  ,  51.  ,  59.  ,
          0.5 ,   0.51,   0.52,   0.53,   0.54],
       [  4.  ,  12.  ,  20.  ,  28.  , -99.  ,  44.  ,  52.  ,  60.  ,
          0.55,   0.56,   0.57,   0.58,   0.59],
       [  5.  , -99.  ,  21.  ,  29.  , -99.  ,  45.  , -99.  ,  61.  ,
          0.6 ,   0.61,   0.62,   0.63,   0.64],
       [  6.  ,  14.  ,  22.  , -99.  , -99.  ,  46.  ,  54.  ,  62.  ,
          0.65,   0.66,   0.67,   0.68,   0.69],
       [  7.  ,  15.  , -99.  , -99.  , -99.  ,  47.  ,  55.  , -99.  ,
          0.7 ,   0.71,   0.72,   0.73,   0.74],
       [  8.  ,  16.  ,  24.  , -99.  ,  40.  ,  48.  ,  56.  ,  64.  ,
          0.75,   0.76,   0.77,   0.78,   0.79]])

### iii. Agregar una línea al final con el promedio de cada columna


In [105]:
#Esta función regresa el promedio de los elementos del arreglo
prom_col = np.mean(matriz, axis = 0)   
prom_col

#Lo agregamos a una línea final de nuestra matriz
matriz1 = np.append(matriz,prom_col).reshape(9,13)
matriz1

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ],
       [  8.   ,  16.   ,  24.   , -99.   ,  40.   ,  48.   , 

### iv. Agregar una columna al final con el valor máximo de cada fila



In [106]:
#Incluye la fila de promedios
fila_valormax = np.max(matriz1, axis=1)
#b=fila_valormax.T
#b
matriz2 = np.insert(matriz1, [13], fila_valormax.reshape(9,1), axis=1)
matriz2

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,  57.   ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,  58.   ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ,  59.   ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,  60.   ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,  61.   ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,  62.   ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,  55.   ],

### v. Guardar en un archivo

In [107]:
np.savetxt('matriz.csv', matriz2, delimiter=',', fmt='%.2f')